// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcbmgiixzyznbqzfhprr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjYm1naWl4enl6bmJxemZocHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTQyMDMsImV4cCI6MjA3NDY3MDIwM30.NrDP0sn0tMJydnrv0gg3woqyxhzFs9aaN3V3B7Wr5Hg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});